#!/bin/sh
# Usage: git-deploy [make arguments e.g. -j8]
# This script will deploy the main branch to gh-pages

set -e
REF="$(git symbolic-ref --short HEAD)"

git checkout gh-pages
git rebase main
make "$@"
git push -f
git checkout "$REF"
